# Generated by Django 6.0.3 on 2026-04-08 03:43

from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations, models


def create_users_for_customers(apps, schema_editor):
    User = apps.get_model('core', 'User')

    with schema_editor.connection.cursor() as cursor:
        cursor.execute('SELECT id FROM store_customer')
        customer_ids = [row[0] for row in cursor.fetchall()]

    for customer_id in customer_ids:
        username = f'customer_{customer_id}'
        email = f'customer_{customer_id}@example.com'

        user, created = User.objects.get_or_create(
            username=username,
            defaults={'email': email, 'password': make_password(None)},
        )

        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                'UPDATE store_customer SET user_id = %s WHERE id = %s',
                [user.id, customer_id],
            )


def drop_legacy_customer_columns(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        for column in ('email', 'first_name', 'last_name'):
            cursor.execute('SHOW COLUMNS FROM store_customer LIKE %s', [column])
            if cursor.fetchone():
                cursor.execute(f'ALTER TABLE store_customer DROP COLUMN {column}')


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_cartitem_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='customer',
                    name='email',
                ),
                migrations.RemoveField(
                    model_name='customer',
                    name='first_name',
                ),
                migrations.RemoveField(
                    model_name='customer',
                    name='last_name',
                ),
                migrations.AddField(
                    model_name='customer',
                    name='user',
                    field=models.OneToOneField(null=True, on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
                migrations.AlterField(
                    model_name='customer',
                    name='user',
                    field=models.OneToOneField(on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            database_operations=[
                migrations.RunPython(drop_legacy_customer_columns, migrations.RunPython.noop),
                migrations.RunPython(create_users_for_customers, migrations.RunPython.noop),
                migrations.RunSQL(
                    sql='ALTER TABLE store_customer MODIFY user_id bigint NOT NULL',
                    reverse_sql='ALTER TABLE store_customer MODIFY user_id bigint NULL',
                ),
            ],
        ),
    ]
